sudo: false
language: ruby
rvm:
- 2.4.3
before_install: gem install bundler -v 1.16.0
deploy:
  provider: rubygems
  api_key:
    secure: UE5A71MwHTf57ohHMPO6J1+u3n0YKMrXNhiiurgBDWqJqkv1X5KGUJF+MKE/9s0Y0jLcm8+qT3EipRVoxGXR8kHBa+8qt0KzTM9hZBZmmdAmPSWo2/sMJ8+AvW31zRSVU4UA0i4GNcnS//PJTrql5e6FYoyAyrarHCVqXnQYqX0GiywquJfXPjWNPRYZZFbKqvYYJgmUiawJbJe2L9Q6VR9vom//wAgz+cizBnsi0xDp6CD2qw6FcuU5T0/7om/SmnTwz5570RngzwraZFDmEMupL2jW14FijqZLEFCz+NTpxxjp6cRhjGMi9kcsgXJ0ltUINn5b62HHUjPes2UFlpfF62a9TUj48K20xwlYJT2iU7PfeZUWK0qTpejJCfsTC+ylCx6k1zpH/ePmhUTOXLgF0oVx6vdbHCOp7U5eObEk00JKHWFIXOV8qPSgGC3JUloY6xGEJS4V//6l/I/4oqkA+qZGAzVY2xbznh+3JuSrBorqH9xZg0pHePH1CHcKbu0p3v//JbjNMst1KaUKOWC7S8Eu9psktxDdaPDu2ijWYVWqBzquU1s79ft7smnsGU8hxtUdinMDSMWnSvZU79dssfq52rTgUnaP528j72KtxLMYuyxn7Q9twx3Yi2v9vkMZUTreCuMppjqIfOZTuCmYJs+jRyYxVxsj5E32Of8=
  gem: net-address
  on:
    tags: true
    repo: pwojcieszonek/net-address
